using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EntglDb.Persistence.EntityFramework.Entities;

/// <summary>
/// Entity Framework entity representing an operation log entry.
/// </summary>
[Table("Oplog")]
public class OplogEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for this oplog entry.
    /// Auto-generated by the database.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the collection name.
    /// </summary>
    [Required]
    [MaxLength(256)]
    public string Collection { get; set; } = "";

    /// <summary>
    /// Gets or sets the document key.
    /// </summary>
    [Required]
    [MaxLength(256)]
    public string Key { get; set; } = "";

    /// <summary>
    /// Gets or sets the operation type (0 = Put, 1 = Delete).
    /// </summary>
    public int Operation { get; set; }

    /// <summary>
    /// Gets or sets the payload JSON (null for Delete operations).
    /// </summary>
    public string? PayloadJson { get; set; }

    /// <summary>
    /// Gets or sets the physical time component of the HLC timestamp.
    /// </summary>
    public long TimestampPhysicalTime { get; set; }

    /// <summary>
    /// Gets or sets the logical counter component of the HLC timestamp.
    /// </summary>
    public int TimestampLogicalCounter { get; set; }

    /// <summary>
    /// Gets or sets the node ID component of the HLC timestamp.
    /// </summary>
    [Required]
    [MaxLength(256)]
    public string TimestampNodeId { get; set; } = "";
}
